### ISSUE TITLE
Alpha ToDo List

### ISSUE THREAD

**Issue by natelindev** [natelindev/lonefire-legacy#1]
##### HomePage

- [x] change margin to 15px
- [x] Add Pagination of Articles
- [x] Add tag display on card top
- [x] Make Home Page About Me  content configurable
- [x] Make Friends configurable

##### Article View Page

- [x] Fix the misalignment of addtime & author
- [x] Add Floating(float only when scroll to certian postition and end at certain position) sidebar with scrollpsy effect as catalog
- [x] Add shareJs for sharing
- [x] Add Like button & use cookies to prevent muilple likes.
- [x] Align image ceneter & add shadow-lg to it

##### Manage Page

- [x] Add left floating side bar for switch of manage items
- [x] Add user manage page 
- [x] Add HomePage & About Page Configuration content

##### Archive Page

- [x] Use Timeline to Display All Articles with horizontal style with pagination
