### ISSUE TITLE
1.0 ToDo List

### ISSUE THREAD

**Issue by natelindev** [natelindev/lonefire-legacy#3]
##### System wide

- [ ] Oauth 2.0 for major 3rd parties
- [ ] Tag Editing js for article
- [ ] Online lightweight md editor
- [ ] img deletion js for article edit
- [ ] Floating navbar behaviour
- [ ] secondary title for every article.
- [ ] Full Globalization implmentation for easy switch of CN & ENG
